language: go
sudo: false
go:
- 1.13.x
go_import_path: github.com/timsolov/rest-query-parser
install:
- go get -t -v ./...
- go get -u honnef.co/go/tools/cmd/staticcheck
- go get -u github.com/client9/misspell/cmd/misspell
before_script:
- $(exit $(go fmt ./... | wc -l))
- go vet ./...
- find . -type f -name "*.go" | xargs misspell -error -locale US
- staticcheck ./...
script:
- go test -i -v ./...
- go test -v -race ./...
after_success:
- ./scripts/cov.sh TRAVIS